from telebot.types import KeyboardButton, ReplyKeyboardMarkup

help_button = KeyboardButton("/help")
new_button = KeyboardButton("/new_story")
end_button = KeyboardButton("/end")
begin_button = KeyboardButton("/begin")
story_button = KeyboardButton("/whole_story")
tokens_button = KeyboardButton("/all_tokens")
genre1_button = KeyboardButton("Хоррор")
genre2_button = KeyboardButton("Фантастика")
genre3_button = KeyboardButton("Детектив")
genre4_button = KeyboardButton("Комедия")
person1_button = KeyboardButton("Доктор Холмс")
person2_button = KeyboardButton("Гарри Поттер")
person3_button = KeyboardButton("Бабадук")
person4_button = KeyboardButton("Павел Воля")
setting1_button = KeyboardButton("Город")
setting2_button = KeyboardButton("Магическая академия")
setting3_button = KeyboardButton("Заброшка")
setting4_button = KeyboardButton("Парк развлечений")

genre_markup = ReplyKeyboardMarkup(resize_keyboard=True)
genre_markup.add(genre1_button, genre2_button, genre3_button, genre4_button)
person_markup = ReplyKeyboardMarkup(resize_keyboard=True)
person_markup.add(person1_button, person2_button, person3_button, person4_button)
setting_markup = ReplyKeyboardMarkup(resize_keyboard=True)
setting_markup.add(setting1_button, setting2_button, setting3_button, setting4_button)
